/**
 * @file include/dbschema/dbGrpOffset.h
 * @brief This generated file contains group and datapoint Id offsets.
 * 
 * This file is automatically generated and should not be edited manually.

 * Generated using the following input files:
 *   xslt/dbGrpOffset_h.xsl : 4478 bytes, CRC32 = 2657252998 
 *   relay-groups.xml : 623536 bytes, CRC32 = 2339814384
 * 
 * Generated from the following database extract:
 *   Db Version : 28.0
 *   Db Tags    : NEW_ARCH,RC20-Security,RC20_USBOC,GooseSqNum,SdCard,VerizonAPN,Large_DbClientId,DB28_OSM_PART_CODES,DIR_POWER,MultiMaster60870,PIN_PUK,CBF_NOTICE,PMU_Retransmission,WEBSERVER
 *   Db Model   : RC20
 * 
 * @cond DO_NOT_DOCUMENT   Doxygen documentation is not required.
 */
#ifndef _DBSCHEMA_INCLUDE_DBSCHEMA_DBGRPOFFSET_H_
#define _DBSCHEMA_INCLUDE_DBSCHEMA_DBGRPOFFSET_H_

/* Base and Max datapoint ID for the Groups
 *      Macro name                           DataPoint ID         Decimal */
#define DPoint_ProtGroup1_BASE               ((DpId) 0x9D)     // 157
#define DPoint_ProtGroup1_MAX                ((DpId) 0x1AA)    // 426

#define DPoint_ProtGroup2_BASE               ((DpId) 0x2E8)    // 744
#define DPoint_ProtGroup2_MAX                ((DpId) 0x3F5)    // 1013

#define DPoint_ProtGroup3_BASE               ((DpId) 0x478)    // 1144
#define DPoint_ProtGroup3_MAX                ((DpId) 0x585)    // 1413

#define DPoint_ProtGroup4_BASE               ((DpId) 0x608)    // 1544
#define DPoint_ProtGroup4_MAX                ((DpId) 0x715)    // 1813

#define DPoint_CommsGroup1_BASE              ((DpId) 0x106F)   // 4207
#define DPoint_CommsGroup1_MAX               ((DpId) 0x10CC)   // 4300

#define DPoint_CommsGroup2_BASE              ((DpId) 0x1137)   // 4407
#define DPoint_CommsGroup2_MAX               ((DpId) 0x1194)   // 4500

#define DPoint_CommsGroup3_BASE              ((DpId) 0x11FF)   // 4607
#define DPoint_CommsGroup3_MAX               ((DpId) 0x125C)   // 4700

#define DPoint_CommsGroup4_BASE              ((DpId) 0x12C7)   // 4807
#define DPoint_CommsGroup4_MAX               ((DpId) 0x1324)   // 4900

#define DPoint_CommsGroup5_BASE              ((DpId) 0x15AC)   // 5548
#define DPoint_CommsGroup5_MAX               ((DpId) 0x1609)   // 5641

#define DPoint_CommsGroup6_BASE              ((DpId) 0x1674)   // 5748
#define DPoint_CommsGroup6_MAX               ((DpId) 0x16D1)   // 5841

#define DPoint_CommsGroup7_BASE              ((DpId) 0x173C)   // 5948
#define DPoint_CommsGroup7_MAX               ((DpId) 0x1799)   // 6041

#define DPoint_CommsGroup8_BASE              ((DpId) 0x1804)   // 6148
#define DPoint_CommsGroup8_MAX               ((DpId) 0x1861)   // 6241

#define DPoint_CommsGroup11_BASE             ((DpId) 0x1B55)   // 6997
#define DPoint_CommsGroup11_MAX              ((DpId) 0x1BB2)   // 7090

#define DPoint_CommsGroup12_BASE             ((DpId) 0x233A)   // 9018
#define DPoint_CommsGroup12_MAX              ((DpId) 0x2397)   // 9111

#define DPoint_CommsGroup13_BASE             ((DpId) 0x24F2)   // 9458
#define DPoint_CommsGroup13_MAX              ((DpId) 0x254F)   // 9551

#define DPoint_CommsGroup14_BASE             ((DpId) 0x2B4F)   // 11087
#define DPoint_CommsGroup14_MAX              ((DpId) 0x2BAC)   // 11180

#define DPoint_CommsStatusGroup1_BASE        ((DpId) 0xE91)    // 3729
#define DPoint_CommsStatusGroup1_MAX         ((DpId) 0xEAB)    // 3755

#define DPoint_CommsStatusGroup2_BASE        ((DpId) 0xEE1)    // 3809
#define DPoint_CommsStatusGroup2_MAX         ((DpId) 0xEFB)    // 3835

#define DPoint_CommsStatusGroup3_BASE        ((DpId) 0xF31)    // 3889
#define DPoint_CommsStatusGroup3_MAX         ((DpId) 0xF4B)    // 3915

#define DPoint_CommsStatusGroup4_BASE        ((DpId) 0xF81)    // 3969
#define DPoint_CommsStatusGroup4_MAX         ((DpId) 0xF9B)    // 3995

#define DPoint_CommsStatusGroup5_BASE        ((DpId) 0x13CE)   // 5070
#define DPoint_CommsStatusGroup5_MAX         ((DpId) 0x13E8)   // 5096

#define DPoint_CommsStatusGroup6_BASE        ((DpId) 0x141D)   // 5149
#define DPoint_CommsStatusGroup6_MAX         ((DpId) 0x1437)   // 5175

#define DPoint_CommsStatusGroup7_BASE        ((DpId) 0x146C)   // 5228
#define DPoint_CommsStatusGroup7_MAX         ((DpId) 0x1486)   // 5254

#define DPoint_CommsStatusGroup8_BASE        ((DpId) 0x14BC)   // 5308
#define DPoint_CommsStatusGroup8_MAX         ((DpId) 0x14D6)   // 5334

#define DPoint_CommsStatusGroup11_BASE       ((DpId) 0x1ADD)   // 6877
#define DPoint_CommsStatusGroup11_MAX        ((DpId) 0x1AF7)   // 6903

#define DPoint_CommsStatusGroup12_BASE       ((DpId) 0x2402)   // 9218
#define DPoint_CommsStatusGroup12_MAX        ((DpId) 0x241C)   // 9244

#define DPoint_CommsStatusGroup13_BASE       ((DpId) 0x2452)   // 9298
#define DPoint_CommsStatusGroup13_MAX        ((DpId) 0x246C)   // 9324

#define DPoint_CommsStatusGroup14_BASE       ((DpId) 0x2AD7)   // 10967
#define DPoint_CommsStatusGroup14_MAX        ((DpId) 0x2AF1)   // 10993

#define DPoint_CommsCmdGroup1_BASE           ((DpId) 0xFD1)    // 4049
#define DPoint_CommsCmdGroup1_MAX            ((DpId) 0xFD4)    // 4052

#define DPoint_CommsCmdGroup2_BASE           ((DpId) 0xFF8)    // 4088
#define DPoint_CommsCmdGroup2_MAX            ((DpId) 0xFFB)    // 4091

#define DPoint_CommsCmdGroup3_BASE           ((DpId) 0x1020)   // 4128
#define DPoint_CommsCmdGroup3_MAX            ((DpId) 0x1023)   // 4131

#define DPoint_CommsCmdGroup4_BASE           ((DpId) 0x1048)   // 4168
#define DPoint_CommsCmdGroup4_MAX            ((DpId) 0x104B)   // 4171

#define DPoint_CommsCmdGroup5_BASE           ((DpId) 0x150C)   // 5388
#define DPoint_CommsCmdGroup5_MAX            ((DpId) 0x150F)   // 5391

#define DPoint_CommsCmdGroup6_BASE           ((DpId) 0x1534)   // 5428
#define DPoint_CommsCmdGroup6_MAX            ((DpId) 0x1537)   // 5431

#define DPoint_CommsCmdGroup7_BASE           ((DpId) 0x155C)   // 5468
#define DPoint_CommsCmdGroup7_MAX            ((DpId) 0x155F)   // 5471

#define DPoint_CommsCmdGroup8_BASE           ((DpId) 0x1584)   // 5508
#define DPoint_CommsCmdGroup8_MAX            ((DpId) 0x1587)   // 5511

#define DPoint_CommsCmdGroup11_BASE          ((DpId) 0x1B2D)   // 6957
#define DPoint_CommsCmdGroup11_MAX           ((DpId) 0x1B30)   // 6960

#define DPoint_CommsCmdGroup12_BASE          ((DpId) 0x24A2)   // 9378
#define DPoint_CommsCmdGroup12_MAX           ((DpId) 0x24A5)   // 9381

#define DPoint_CommsCmdGroup13_BASE          ((DpId) 0x24CA)   // 9418
#define DPoint_CommsCmdGroup13_MAX           ((DpId) 0x24CD)   // 9421

#define DPoint_CommsCmdGroup14_BASE          ((DpId) 0x2B27)   // 11047
#define DPoint_CommsCmdGroup14_MAX           ((DpId) 0x2B2A)   // 11050

#define DPoint_ExtProtGroup1_BASE            ((DpId) 0x19C8)   // 6600
#define DPoint_ExtProtGroup1_MAX             ((DpId) 0x19F8)   // 6648

#define DPoint_ExtProtGroup2_BASE            ((DpId) 0x19FA)   // 6650
#define DPoint_ExtProtGroup2_MAX             ((DpId) 0x1A2A)   // 6698

#define DPoint_ExtProtGroup3_BASE            ((DpId) 0x1A2C)   // 6700
#define DPoint_ExtProtGroup3_MAX             ((DpId) 0x1A5C)   // 6748

#define DPoint_ExtProtGroup4_BASE            ((DpId) 0x1A5E)   // 6750
#define DPoint_ExtProtGroup4_MAX             ((DpId) 0x1A8E)   // 6798

#define DPoint_Ext2ProtGroup1_BASE           ((DpId) 0x1C46)   // 7238
#define DPoint_Ext2ProtGroup1_MAX            ((DpId) 0x1D0A)   // 7434

#define DPoint_Ext2ProtGroup2_BASE           ((DpId) 0x1D0E)   // 7438
#define DPoint_Ext2ProtGroup2_MAX            ((DpId) 0x1DD2)   // 7634

#define DPoint_Ext2ProtGroup3_BASE           ((DpId) 0x1DD6)   // 7638
#define DPoint_Ext2ProtGroup3_MAX            ((DpId) 0x1E9A)   // 7834

#define DPoint_Ext2ProtGroup4_BASE           ((DpId) 0x1E9E)   // 7838
#define DPoint_Ext2ProtGroup4_MAX            ((DpId) 0x1F62)   // 8034

#define DPoint_Ext3ProtGroup1_BASE           ((DpId) 0x261A)   // 9754
#define DPoint_Ext3ProtGroup1_MAX            ((DpId) 0x265E)   // 9822

#define DPoint_Ext3ProtGroup2_BASE           ((DpId) 0x26E2)   // 9954
#define DPoint_Ext3ProtGroup2_MAX            ((DpId) 0x2726)   // 10022

#define DPoint_Ext3ProtGroup3_BASE           ((DpId) 0x27AA)   // 10154
#define DPoint_Ext3ProtGroup3_MAX            ((DpId) 0x27EE)   // 10222

#define DPoint_Ext3ProtGroup4_BASE           ((DpId) 0x2872)   // 10354
#define DPoint_Ext3ProtGroup4_MAX            ((DpId) 0x28B6)   // 10422

#define DPoint_RG1C1_BASE                    ((DpId) 0x2CAB)   // 11435
#define DPoint_RG1C1_MAX                     ((DpId) 0x2CBA)   // 11450

#define DPoint_RG1C2_BASE                    ((DpId) 0x2CC4)   // 11460
#define DPoint_RG1C2_MAX                     ((DpId) 0x2CD3)   // 11475

#define DPoint_RG2C1_BASE                    ((DpId) 0x2CDD)   // 11485
#define DPoint_RG2C1_MAX                     ((DpId) 0x2CEC)   // 11500

#define DPoint_RG2C2_BASE                    ((DpId) 0x2CF6)   // 11510
#define DPoint_RG2C2_MAX                     ((DpId) 0x2D05)   // 11525

#define DPoint_C1_BASE                       ((DpId) 0x2DA3)   // 11683
#define DPoint_C1_MAX                        ((DpId) 0x0)      // 

#define DPoint_C2_BASE                       ((DpId) 0x2DBC)   // 11708
#define DPoint_C2_MAX                        ((DpId) 0x0)      // 


/*   ProtectionStruct: Datapoint ID Offset from Base ID   */
#define DPOff_OcAt                           0x0
#define DPOff_OcDnd                          0x1
#define DPOff_EfAt                           0x2
#define DPOff_EfDnd                          0x3
#define DPOff_SefAt                          0x4
#define DPOff_SefDnd                         0x5
#define DPOff_ArOCEF_ZSCmode                 0x6
#define DPOff_VrcEnable                      0x7
#define DPOff_ArOCEF_Trec1                   0x9
#define DPOff_ArOCEF_Trec2                   0xA
#define DPOff_ArOCEF_Trec3                   0xB
#define DPOff_ResetTime                      0xC
#define DPOff_TtaMode                        0xD
#define DPOff_TtaTime                        0xE
#define DPOff_SstOcForward                   0xF
#define DPOff_EftEnable                      0x10
#define DPOff_ClpClm                         0x11
#define DPOff_ClpTcl                         0x12
#define DPOff_ClpTrec                        0x13
#define DPOff_IrrIrm                         0x14
#define DPOff_IrrTir                         0x15
#define DPOff_VrcMode                        0x16
#define DPOff_VrcUMmin                       0x17
#define DPOff_AbrMode                        0x18
#define DPOff_OC1F_Ip                        0x19
#define DPOff_OC1F_Tcc                       0x1A
#define DPOff_OC1F_TDtMin                    0x1B
#define DPOff_OC1F_TDtRes                    0x1C
#define DPOff_OC1F_Tm                        0x1D
#define DPOff_OC1F_Imin                      0x1E
#define DPOff_OC1F_Tmin                      0x1F
#define DPOff_OC1F_Tmax                      0x20
#define DPOff_OC1F_Ta                        0x21
#define DPOff_OC1F_ImaxEn                    0x23
#define DPOff_OC1F_Imax                      0x24
#define DPOff_OC1F_DirEn                     0x25
#define DPOff_OC1F_Tr1                       0x26
#define DPOff_OC1F_Tr2                       0x27
#define DPOff_OC1F_Tr3                       0x28
#define DPOff_OC1F_Tr4                       0x29
#define DPOff_OC1F_TccUD                     0x2A
#define DPOff_OC2F_Ip                        0x2B
#define DPOff_OC2F_Tcc                       0x2C
#define DPOff_OC2F_TDtMin                    0x2D
#define DPOff_OC2F_TDtRes                    0x2E
#define DPOff_OC2F_Tm                        0x2F
#define DPOff_OC2F_Imin                      0x30
#define DPOff_OC2F_Tmin                      0x31
#define DPOff_OC2F_Tmax                      0x32
#define DPOff_OC2F_Ta                        0x33
#define DPOff_EftTripCount                   0x34
#define DPOff_OC2F_ImaxEn                    0x35
#define DPOff_OC2F_Imax                      0x36
#define DPOff_OC2F_DirEn                     0x37
#define DPOff_OC2F_Tr1                       0x38
#define DPOff_OC2F_Tr2                       0x39
#define DPOff_OC2F_Tr3                       0x3A
#define DPOff_OC2F_Tr4                       0x3B
#define DPOff_OC2F_TccUD                     0x3C
#define DPOff_OC3F_Ip                        0x3D
#define DPOff_OC3F_TDtMin                    0x3E
#define DPOff_OC3F_TDtRes                    0x3F
#define DPOff_OC3F_DirEn                     0x40
#define DPOff_OC3F_Tr1                       0x41
#define DPOff_OC3F_Tr2                       0x42
#define DPOff_OC3F_Tr3                       0x43
#define DPOff_OC3F_Tr4                       0x44
#define DPOff_OC1R_Ip                        0x45
#define DPOff_OC1R_Tcc                       0x46
#define DPOff_OC1R_TDtMin                    0x47
#define DPOff_OC1R_TDtRes                    0x48
#define DPOff_OC1R_Tm                        0x49
#define DPOff_OC1R_Imin                      0x4A
#define DPOff_OC1R_Tmin                      0x4B
#define DPOff_OC1R_Tmax                      0x4C
#define DPOff_OC1R_Ta                        0x4D
#define DPOff_EftTripWindow                  0x4E
#define DPOff_OC1R_ImaxEn                    0x4F
#define DPOff_OC1R_Imax                      0x50
#define DPOff_OC1R_DirEn                     0x51
#define DPOff_OC1R_Tr1                       0x52
#define DPOff_OC1R_Tr2                       0x53
#define DPOff_OC1R_Tr3                       0x54
#define DPOff_OC1R_Tr4                       0x55
#define DPOff_OC1R_TccUD                     0x56
#define DPOff_OC2R_Ip                        0x57
#define DPOff_OC2R_Tcc                       0x58
#define DPOff_OC2R_TDtMin                    0x59
#define DPOff_OC2R_TDtRes                    0x5A
#define DPOff_OC2R_Tm                        0x5B
#define DPOff_OC2R_Imin                      0x5C
#define DPOff_OC2R_Tmin                      0x5D
#define DPOff_OC2R_Tmax                      0x5E
#define DPOff_OC2R_Ta                        0x5F
#define DPOff_DEPRECATED_G1OC2R_Tres         0x60
#define DPOff_OC2R_ImaxEn                    0x61
#define DPOff_OC2R_Imax                      0x62
#define DPOff_OC2R_DirEn                     0x63
#define DPOff_OC2R_Tr1                       0x64
#define DPOff_OC2R_Tr2                       0x65
#define DPOff_OC2R_Tr3                       0x66
#define DPOff_OC2R_Tr4                       0x67
#define DPOff_OC2R_TccUD                     0x68
#define DPOff_OC3R_Ip                        0x69
#define DPOff_OC3R_TDtMin                    0x6A
#define DPOff_OC3R_TDtRes                    0x6B
#define DPOff_OC3R_DirEn                     0x6C
#define DPOff_OC3R_Tr1                       0x6D
#define DPOff_OC3R_Tr2                       0x6E
#define DPOff_OC3R_Tr3                       0x6F
#define DPOff_OC3R_Tr4                       0x70
#define DPOff_EF1F_Ip                        0x71
#define DPOff_EF1F_Tcc                       0x72
#define DPOff_EF1F_TDtMin                    0x73
#define DPOff_EF1F_TDtRes                    0x74
#define DPOff_EF1F_Tm                        0x75
#define DPOff_EF1F_Imin                      0x76
#define DPOff_EF1F_Tmin                      0x77
#define DPOff_EF1F_Tmax                      0x78
#define DPOff_EF1F_Ta                        0x79
#define DPOff_DEPRECATED_G1EF1F_Tres         0x7A
#define DPOff_EF1F_ImaxEn                    0x7B
#define DPOff_EF1F_Imax                      0x7C
#define DPOff_EF1F_DirEn                     0x7D
#define DPOff_EF1F_Tr1                       0x7E
#define DPOff_EF1F_Tr2                       0x7F
#define DPOff_EF1F_Tr3                       0x80
#define DPOff_EF1F_Tr4                       0x81
#define DPOff_EF1F_TccUD                     0x82
#define DPOff_EF2F_Ip                        0x83
#define DPOff_EF2F_Tcc                       0x84
#define DPOff_EF2F_TDtMin                    0x85
#define DPOff_EF2F_TDtRes                    0x86
#define DPOff_EF2F_Tm                        0x87
#define DPOff_EF2F_Imin                      0x88
#define DPOff_EF2F_Tmin                      0x89
#define DPOff_EF2F_Tmax                      0x8A
#define DPOff_EF2F_Ta                        0x8B
#define DPOff_DEPRECATED_G1EF2F_Tres         0x8C
#define DPOff_EF2F_ImaxEn                    0x8D
#define DPOff_EF2F_Imax                      0x8E
#define DPOff_EF2F_DirEn                     0x8F
#define DPOff_EF2F_Tr1                       0x90
#define DPOff_EF2F_Tr2                       0x91
#define DPOff_EF2F_Tr3                       0x92
#define DPOff_EF2F_Tr4                       0x93
#define DPOff_EF2F_TccUD                     0x94
#define DPOff_EF3F_Ip                        0x95
#define DPOff_EF3F_TDtMin                    0x96
#define DPOff_EF3F_TDtRes                    0x97
#define DPOff_EF3F_DirEn                     0x98
#define DPOff_EF3F_Tr1                       0x99
#define DPOff_EF3F_Tr2                       0x9A
#define DPOff_EF3F_Tr3                       0x9B
#define DPOff_EF3F_Tr4                       0x9C
#define DPOff_EF1R_Ip                        0x9D
#define DPOff_EF1R_Tcc                       0x9E
#define DPOff_EF1R_TDtMin                    0x9F
#define DPOff_EF1R_TDtRes                    0xA0
#define DPOff_EF1R_Tm                        0xA1
#define DPOff_EF1R_Imin                      0xA2
#define DPOff_EF1R_Tmin                      0xA3
#define DPOff_EF1R_Tmax                      0xA4
#define DPOff_EF1R_Ta                        0xA5
#define DPOff_DEPRECATED_G1EF1R_Tres         0xA6
#define DPOff_EF1R_ImaxEn                    0xA7
#define DPOff_EF1R_Imax                      0xA8
#define DPOff_EF1R_DirEn                     0xA9
#define DPOff_EF1R_Tr1                       0xAA
#define DPOff_EF1R_Tr2                       0xAB
#define DPOff_EF1R_Tr3                       0xAC
#define DPOff_EF1R_Tr4                       0xAD
#define DPOff_EF1R_TccUD                     0xAE
#define DPOff_EF2R_Ip                        0xAF
#define DPOff_EF2R_Tcc                       0xB0
#define DPOff_EF2R_TDtMin                    0xB1
#define DPOff_EF2R_TDtRes                    0xB2
#define DPOff_EF2R_Tm                        0xB3
#define DPOff_EF2R_Imin                      0xB4
#define DPOff_EF2R_Tmin                      0xB5
#define DPOff_EF2R_Tmax                      0xB6
#define DPOff_EF2R_Ta                        0xB7
#define DPOff_DEPRECATED_G1EF2R_Tres         0xB8
#define DPOff_EF2R_ImaxEn                    0xB9
#define DPOff_EF2R_Imax                      0xBA
#define DPOff_EF2R_DirEn                     0xBB
#define DPOff_EF2R_Tr1                       0xBC
#define DPOff_EF2R_Tr2                       0xBD
#define DPOff_EF2R_Tr3                       0xBE
#define DPOff_EF2R_Tr4                       0xBF
#define DPOff_EF2R_TccUD                     0xC0
#define DPOff_EF3R_Ip                        0xC1
#define DPOff_EF3R_TDtMin                    0xC2
#define DPOff_EF3R_TDtRes                    0xC3
#define DPOff_EF3R_DirEn                     0xC4
#define DPOff_EF3R_Tr1                       0xC5
#define DPOff_EF3R_Tr2                       0xC6
#define DPOff_EF3R_Tr3                       0xC7
#define DPOff_EF3R_Tr4                       0xC8
#define DPOff_SEFF_Ip                        0xC9
#define DPOff_SEFF_TDtMin                    0xCA
#define DPOff_SEFF_TDtRes                    0xCB
#define DPOff_SEFF_DirEn                     0xCC
#define DPOff_SEFF_Tr1                       0xCD
#define DPOff_SEFF_Tr2                       0xCE
#define DPOff_SEFF_Tr3                       0xCF
#define DPOff_SEFF_Tr4                       0xD0
#define DPOff_SEFR_Ip                        0xD1
#define DPOff_SEFR_TDtMin                    0xD2
#define DPOff_SEFR_TDtRes                    0xD3
#define DPOff_SEFR_DirEn                     0xD4
#define DPOff_SEFR_Tr1                       0xD5
#define DPOff_SEFR_Tr2                       0xD6
#define DPOff_SEFR_Tr3                       0xD7
#define DPOff_SEFR_Tr4                       0xD8
#define DPOff_OcLl_Ip                        0xD9
#define DPOff_OcLl_TDtMin                    0xDA
#define DPOff_OcLl_TDtRes                    0xDB
#define DPOff_EfLl_Ip                        0xDC
#define DPOff_EfLl_TDtMin                    0xDD
#define DPOff_EfLl_TDtRes                    0xDE
#define DPOff_Uv1_Um                         0xDF
#define DPOff_Uv1_TDtMin                     0xE0
#define DPOff_Uv1_TDtRes                     0xE1
#define DPOff_Uv1_Trm                        0xE2
#define DPOff_Uv2_Um                         0xE3
#define DPOff_Uv2_TDtMin                     0xE4
#define DPOff_Uv2_TDtRes                     0xE5
#define DPOff_Uv2_Trm                        0xE6
#define DPOff_Uv3_TDtMin                     0xE7
#define DPOff_Uv3_TDtRes                     0xE8
#define DPOff_Uv3_Trm                        0xE9
#define DPOff_Ov1_Um                         0xEA
#define DPOff_Ov1_TDtMin                     0xEB
#define DPOff_Ov1_TDtRes                     0xEC
#define DPOff_Ov1_Trm                        0xED
#define DPOff_Ov2_Um                         0xEE
#define DPOff_Ov2_TDtMin                     0xEF
#define DPOff_Ov2_TDtRes                     0xF0
#define DPOff_Ov2_Trm                        0xF1
#define DPOff_Uf_Fp                          0xF2
#define DPOff_Uf_TDtMin                      0xF3
#define DPOff_Uf_TDtRes                      0xF4
#define DPOff_Uf_Trm                         0xF5
#define DPOff_Of_Fp                          0xF6
#define DPOff_Of_TDtMin                      0xF7
#define DPOff_Of_TDtRes                      0xF8
#define DPOff_Of_Trm                         0xF9
#define DPOff_DEPRECATED_OC1F_ImaxAbs        0xFA
#define DPOff_DEPRECATED_OC2F_ImaxAbs        0xFB
#define DPOff_DEPRECATED_OC1R_ImaxAbs        0xFC
#define DPOff_DEPRECATED_OC2R_ImaxAbs        0xFD
#define DPOff_DEPRECATED_EF1F_ImaxAbs        0xFE
#define DPOff_DEPRECATED_EF2F_ImaxAbs        0xFF
#define DPOff_DEPRECATED_EF1R_ImaxAbs        0x100
#define DPOff_DEPRECATED_EF2R_ImaxAbs        0x101
#define DPOff_SstEfForward                   0x102
#define DPOff_SstSefForward                  0x103
#define DPOff_AbrTrest                       0x104
#define DPOff_AutoOpenMode                   0x105
#define DPOff_AutoOpenTime                   0x106
#define DPOff_AutoOpenOpns                   0x107
#define DPOff_SstOcReverse                   0x108
#define DPOff_SstEfReverse                   0x109
#define DPOff_SstSefReverse                  0x10A
#define DPOff_ArUVOV_Trec                    0x10B
#define DPOff_GrpName                        0x10C
#define DPOff_GrpDes                         0x10D

/*   mobile: Datapoint ID Offset from Base ID   */
#define DPOff_SerialBaudRate                 0x0
#define DPOff_SerialDuplexType               0x1
#define DPOff_SerialRTSMode                  0x2
#define DPOff_SerialRTSOnLevel               0x3
#define DPOff_SerialDTRMode                  0x4
#define DPOff_SerialDTROnLevel               0x5
#define DPOff_SerialParity                   0x6
#define DPOff_SerialCTSMode                  0x7
#define DPOff_SerialDSRMode                  0x8
#define DPOff_SerialDCDMode                  0x9
#define DPOff_SerialDTRLowTime               0xA
#define DPOff_SerialTxDelay                  0xB
#define DPOff_SerialPreTxTime                0xC
#define DPOff_SerialDCDFallTime              0xD
#define DPOff_SerialCharTimeout              0xE
#define DPOff_SerialPostTxTime               0xF
#define DPOff_SerialInactivityTime           0x10
#define DPOff_SerialCollisionAvoidance       0x11
#define DPOff_SerialMinIdleTime              0x12
#define DPOff_SerialMaxRandomDelay           0x13
#define DPOff_ModemPoweredFromExtLoad        0x14
#define DPOff_ModemUsedWithLeasedLine        0x15
#define DPOff_ModemInitString                0x16
#define DPOff_ModemDialOut                   0x17
#define DPOff_ModemPreDialString             0x18
#define DPOff_ModemDialNumber1               0x19
#define DPOff_ModemDialNumber2               0x1A
#define DPOff_ModemDialNumber3               0x1B
#define DPOff_ModemDialNumber4               0x1C
#define DPOff_ModemDialNumber5               0x1D
#define DPOff_ModemAutoDialInterval          0x1E
#define DPOff_ModemConnectionTimeout         0x1F
#define DPOff_ModemMaxCallDuration           0x20
#define DPOff_ModemResponseTime              0x21
#define DPOff_ModemHangUpCommand             0x22
#define DPOff_ModemOffHookCommand            0x23
#define DPOff_ModemAutoAnswerOn              0x24
#define DPOff_ModemAutoAnswerOff             0x25
#define DPOff_RadioPreamble                  0x26
#define DPOff_RadioPreambleChar              0x27
#define DPOff_RadioPreambleRepeat            0x28
#define DPOff_RadioPreambleLastChar          0x29
#define DPOff_LanSpecifyIP                   0x2A
#define DPOff_LanIPAddr                      0x2B
#define DPOff_LanSubnetMask                  0x2C
#define DPOff_LanDefaultGateway              0x2D
#define DPOff_WlanNetworkSSID                0x2E
#define DPOff_WlanNetworkAuthentication      0x2F
#define DPOff_WlanDataEncryption             0x30
#define DPOff_WlanNetworkKey                 0x31
#define DPOff_WlanKeyIndex                   0x32
#define DPOff_PortLocalRemoteMode            0x33
#define DPOff_GPRSServiceProvider            0x34
#define DPOff_GPRSUserName                   0x37
#define DPOff_GPRSPassWord                   0x38
#define DPOff_SerialDebugMode                0x39
#define DPOff_SerialDebugFileName            0x3A
#define DPOff_GPRSBaudRate                   0x3B
#define DPOff_GPRSConnectionTimeout          0x3C
#define DPOff_DNP3InputPipe                  0x3D
#define DPOff_DNP3OutputPipe                 0x3E
#define DPOff_CMSInputPipe                   0x3F
#define DPOff_CMSOutputPipe                  0x40
#define DPOff_HMIInputPipe                   0x41
#define DPOff_HMIOutputPipe                  0x42
#define DPOff_DNP3ChannelRequest             0x43
#define DPOff_DNP3ChannelOpen                0x44
#define DPOff_CMSChannelRequest              0x45
#define DPOff_CMSChannelOpen                 0x46
#define DPOff_HMIChannelRequest              0x47
#define DPOff_HMIChannelOpen                 0x48
#define DPOff_GPRSUseModemSetting            0x49
#define DPOff_SerialFlowControlMode          0x4A
#define DPOff_SerialDCDControlMode           0x4B
#define DPOff_T10BInputPipe                  0x4C
#define DPOff_T10BOutputPipe                 0x4D
#define DPOff_T10BChannelRequest             0x4E
#define DPOff_T10BChannelOpen                0x4F
#define DPOff_P2PInputPipe                   0x50
#define DPOff_P2POutputPipe                  0x51
#define DPOff_P2PChannelRequest              0x52
#define DPOff_P2PChannelOpen                 0x53
#define DPOff_PGEInputPipe                   0x54
#define DPOff_PGEOutputPipe                  0x55
#define DPOff_PGEChannelRequest              0x56
#define DPOff_PGEChannelOpen                 0x57
#define DPOff_LanProvideIP                   0x58
#define DPOff_LanSpecifyIPv6                 0x59
#define DPOff_LanIPv6Addr                    0x5A
#define DPOff_LanPrefixLength                0x5B
#define DPOff_LanIPv6DefaultGateway          0x5C
#define DPOff_LanIpVersion                   0x5D

/*   CommsStatusStruct: Datapoint ID Offset from Base ID   */
#define DPOff_SerialDTRStatus                0x0
#define DPOff_SerialDSRStatus                0x1
#define DPOff_SerialCDStatus                 0x2
#define DPOff_SerialRTSStatus                0x3
#define DPOff_SerialCTSStatus                0x4
#define DPOff_SerialRIStatus                 0x5
#define DPOff_ConnectionStatus               0x6
#define DPOff_BytesReceivedStatus            0x7
#define DPOff_BytesTransmittedStatus         0x8
#define DPOff_PacketsReceivedStatus          0x9
#define DPOff_PacketsTransmittedStatus       0xA
#define DPOff_ErrorPacketsReceivedStatus     0xB
#define DPOff_ErrorPacketsTransmittedStatus  0xC
#define DPOff_IpAddrStatus                   0xD
#define DPOff_SubnetMaskStatus               0xE
#define DPOff_DefaultGatewayStatus           0xF
#define DPOff_PortDetectedType               0x10
#define DPOff_PortDetectedName               0x11
#define DPOff_SerialTxTestStatus             0x12
#define DPOff_PacketsReceivedStatusIPv6      0x13
#define DPOff_PacketsTransmittedStatusIPv6   0x14
#define DPOff_ErrorPacketsReceivedStatusIPv6 0x15
#define DPOff_ErrorPacketsTransmittedStatusIPv6 0x16
#define DPOff_Ipv6AddrStatus                 0x17
#define DPOff_LanPrefixLengthStatus          0x18
#define DPOff_Ipv6DefaultGatewayStatus       0x19
#define DPOff_IpVersionStatus                0x1A

/*   CommsCmdStruct: Datapoint ID Offset from Base ID   */
#define DPOff_SerialPortTestCmd              0x0
#define DPOff_SerialPortHangupCmd            0x1
#define DPOff_BytesReceivedResetCmd          0x2
#define DPOff_BytesTransmittedResetCmd       0x3

/*   ExtProtectionStruct: Datapoint ID Offset from Base ID   */
#define DPOff_Hrm_VTHD_Mode                  0x0
#define DPOff_Hrm_VTHD_Level                 0x1
#define DPOff_Hrm_VTHD_TDtMin                0x2
#define DPOff_Hrm_ITDD_Mode                  0x3
#define DPOff_Hrm_ITDD_Level                 0x4
#define DPOff_Hrm_ITDD_TDtMin                0x5
#define DPOff_Hrm_Ind_Mode                   0x6
#define DPOff_Hrm_Ind_TDtMin                 0x7
#define DPOff_Hrm_IndA_Name                  0x8
#define DPOff_Hrm_IndA_Level                 0x9
#define DPOff_Hrm_IndB_Name                  0xA
#define DPOff_Hrm_IndB_Level                 0xB
#define DPOff_Hrm_IndC_Name                  0xC
#define DPOff_Hrm_IndC_Level                 0xD
#define DPOff_Hrm_IndD_Name                  0xE
#define DPOff_Hrm_IndD_Level                 0xF
#define DPOff_Hrm_IndE_Name                  0x10
#define DPOff_Hrm_IndE_Level                 0x11
#define DPOff_OCLL1_Ip                       0x12
#define DPOff_OCLL1_Tcc                      0x13
#define DPOff_OCLL1_TDtMin                   0x14
#define DPOff_OCLL1_TDtRes                   0x15
#define DPOff_OCLL1_Tm                       0x16
#define DPOff_OCLL1_Imin                     0x17
#define DPOff_OCLL1_Tmin                     0x18
#define DPOff_OCLL1_Tmax                     0x19
#define DPOff_OCLL1_Ta                       0x1A
#define DPOff_OCLL1_ImaxEn                   0x1B
#define DPOff_OCLL1_Imax                     0x1C
#define DPOff_OCLL1_En                       0x1D
#define DPOff_OCLL1_TccUD                    0x1E
#define DPOff_OCLL2_Ip                       0x1F
#define DPOff_OCLL2_Tcc                      0x20
#define DPOff_OCLL2_TDtMin                   0x21
#define DPOff_OCLL2_TDtRes                   0x22
#define DPOff_OCLL2_Tm                       0x23
#define DPOff_OCLL2_Imin                     0x24
#define DPOff_OCLL2_Tmin                     0x25
#define DPOff_OCLL2_Tmax                     0x26
#define DPOff_OCLL2_Ta                       0x27
#define DPOff_OCLL2_ImaxEn                   0x28
#define DPOff_OCLL2_Imax                     0x29
#define DPOff_OCLL2_En                       0x2A
#define DPOff_OCLL2_TccUD                    0x2B
#define DPOff_OCLL3_En                       0x2C
#define DPOff_AutoClose_En                   0x2D
#define DPOff_AutoClose_Tr                   0x2E
#define DPOff_AutoOpenPowerFlowDirChanged    0x2F
#define DPOff_AutoOpenPowerFlowReduced       0x30

/*   Ext2ProtectionStruct: Datapoint ID Offset from Base ID   */
#define DPOff_NpsAt                          0x0
#define DPOff_NpsDnd                         0x1
#define DPOff_SstNpsForward                  0x2
#define DPOff_SstNpsReverse                  0x3
#define DPOff_NPS1F_Ip                       0x4
#define DPOff_NPS1F_Tcc                      0x5
#define DPOff_NPS1F_TDtMin                   0x6
#define DPOff_NPS1F_TDtRes                   0x7
#define DPOff_NPS1F_Tm                       0x8
#define DPOff_NPS1F_Imin                     0x9
#define DPOff_NPS1F_Tmin                     0xA
#define DPOff_NPS1F_Tmax                     0xB
#define DPOff_NPS1F_Ta                       0xC
#define DPOff_NPS1F_ImaxEn                   0xD
#define DPOff_NPS1F_Imax                     0xE
#define DPOff_NPS1F_DirEn                    0xF
#define DPOff_NPS1F_Tr1                      0x10
#define DPOff_NPS1F_Tr2                      0x11
#define DPOff_NPS1F_Tr3                      0x12
#define DPOff_NPS1F_Tr4                      0x13
#define DPOff_NPS1F_TccUD                    0x14
#define DPOff_NPS2F_Ip                       0x15
#define DPOff_NPS2F_Tcc                      0x16
#define DPOff_NPS2F_TDtMin                   0x17
#define DPOff_NPS2F_TDtRes                   0x18
#define DPOff_NPS2F_Tm                       0x19
#define DPOff_NPS2F_Imin                     0x1A
#define DPOff_NPS2F_Tmin                     0x1B
#define DPOff_NPS2F_Tmax                     0x1C
#define DPOff_NPS2F_Ta                       0x1D
#define DPOff_NPS2F_ImaxEn                   0x1E
#define DPOff_NPS2F_Imax                     0x1F
#define DPOff_NPS2F_DirEn                    0x20
#define DPOff_NPS2F_Tr1                      0x21
#define DPOff_NPS2F_Tr2                      0x22
#define DPOff_NPS2F_Tr3                      0x23
#define DPOff_NPS2F_Tr4                      0x24
#define DPOff_NPS2F_TccUD                    0x25
#define DPOff_NPS3F_Ip                       0x26
#define DPOff_NPS3F_TDtMin                   0x27
#define DPOff_NPS3F_TDtRes                   0x28
#define DPOff_NPS3F_DirEn                    0x29
#define DPOff_NPS3F_Tr1                      0x2A
#define DPOff_NPS3F_Tr2                      0x2B
#define DPOff_NPS3F_Tr3                      0x2C
#define DPOff_NPS3F_Tr4                      0x2D
#define DPOff_NPS1R_Ip                       0x2E
#define DPOff_NPS1R_Tcc                      0x2F
#define DPOff_NPS1R_TDtMin                   0x30
#define DPOff_NPS1R_TDtRes                   0x31
#define DPOff_NPS1R_Tm                       0x32
#define DPOff_NPS1R_Imin                     0x33
#define DPOff_NPS1R_Tmin                     0x34
#define DPOff_NPS1R_Tmax                     0x35
#define DPOff_NPS1R_Ta                       0x36
#define DPOff_NPS1R_ImaxEn                   0x37
#define DPOff_NPS1R_Imax                     0x38
#define DPOff_NPS1R_DirEn                    0x39
#define DPOff_NPS1R_Tr1                      0x3A
#define DPOff_NPS1R_Tr2                      0x3B
#define DPOff_NPS1R_Tr3                      0x3C
#define DPOff_NPS1R_Tr4                      0x3D
#define DPOff_NPS1R_TccUD                    0x3E
#define DPOff_NPS2R_Ip                       0x3F
#define DPOff_NPS2R_Tcc                      0x40
#define DPOff_NPS2R_TDtMin                   0x41
#define DPOff_NPS2R_TDtRes                   0x42
#define DPOff_NPS2R_Tm                       0x43
#define DPOff_NPS2R_Imin                     0x44
#define DPOff_NPS2R_Tmin                     0x45
#define DPOff_NPS2R_Tmax                     0x46
#define DPOff_NPS2R_Ta                       0x47
#define DPOff_NPS2R_ImaxEn                   0x48
#define DPOff_NPS2R_Imax                     0x49
#define DPOff_NPS2R_DirEn                    0x4A
#define DPOff_NPS2R_Tr1                      0x4B
#define DPOff_NPS2R_Tr2                      0x4C
#define DPOff_NPS2R_Tr3                      0x4D
#define DPOff_NPS2R_Tr4                      0x4E
#define DPOff_NPS2R_TccUD                    0x4F
#define DPOff_NPS3R_Ip                       0x50
#define DPOff_NPS3R_TDtMin                   0x51
#define DPOff_NPS3R_TDtRes                   0x52
#define DPOff_NPS3R_DirEn                    0x53
#define DPOff_NPS3R_Tr1                      0x54
#define DPOff_NPS3R_Tr2                      0x55
#define DPOff_NPS3R_Tr3                      0x56
#define DPOff_NPS3R_Tr4                      0x57
#define DPOff_NPSLL1_Ip                      0x58
#define DPOff_NPSLL1_Tcc                     0x59
#define DPOff_NPSLL1_TDtMin                  0x5A
#define DPOff_NPSLL1_TDtRes                  0x5B
#define DPOff_NPSLL1_Tm                      0x5C
#define DPOff_NPSLL1_Imin                    0x5D
#define DPOff_NPSLL1_Tmin                    0x5E
#define DPOff_NPSLL1_Tmax                    0x5F
#define DPOff_NPSLL1_Ta                      0x60
#define DPOff_NPSLL1_ImaxEn                  0x61
#define DPOff_NPSLL1_Imax                    0x62
#define DPOff_NPSLL1_En                      0x63
#define DPOff_NPSLL1_TccUD                   0x64
#define DPOff_NPSLL2_Ip                      0x65
#define DPOff_NPSLL2_Tcc                     0x66
#define DPOff_NPSLL2_TDtMin                  0x67
#define DPOff_NPSLL2_TDtRes                  0x68
#define DPOff_NPSLL2_Tm                      0x69
#define DPOff_NPSLL2_Imin                    0x6A
#define DPOff_NPSLL2_Tmin                    0x6B
#define DPOff_NPSLL2_Tmax                    0x6C
#define DPOff_NPSLL2_Ta                      0x6D
#define DPOff_NPSLL2_ImaxEn                  0x6E
#define DPOff_NPSLL2_Imax                    0x6F
#define DPOff_NPSLL2_En                      0x70
#define DPOff_NPSLL2_TccUD                   0x71
#define DPOff_NPSLL3_Ip                      0x72
#define DPOff_NPSLL3_TDtMin                  0x73
#define DPOff_NPSLL3_TDtRes                  0x74
#define DPOff_NPSLL3_En                      0x75
#define DPOff_EFLL1_Ip                       0x76
#define DPOff_EFLL1_Tcc                      0x77
#define DPOff_EFLL1_TDtMin                   0x78
#define DPOff_EFLL1_TDtRes                   0x79
#define DPOff_EFLL1_Tm                       0x7A
#define DPOff_EFLL1_Imin                     0x7B
#define DPOff_EFLL1_Tmin                     0x7C
#define DPOff_EFLL1_Tmax                     0x7D
#define DPOff_EFLL1_Ta                       0x7E
#define DPOff_EFLL1_ImaxEn                   0x7F
#define DPOff_EFLL1_Imax                     0x80
#define DPOff_EFLL1_En                       0x81
#define DPOff_EFLL1_TccUD                    0x82
#define DPOff_EFLL2_Ip                       0x83
#define DPOff_EFLL2_Tcc                      0x84
#define DPOff_EFLL2_TDtMin                   0x85
#define DPOff_EFLL2_TDtRes                   0x86
#define DPOff_EFLL2_Tm                       0x87
#define DPOff_EFLL2_Imin                     0x88
#define DPOff_EFLL2_Tmin                     0x89
#define DPOff_EFLL2_Tmax                     0x8A
#define DPOff_EFLL2_Ta                       0x8B
#define DPOff_EFLL2_ImaxEn                   0x8C
#define DPOff_EFLL2_Imax                     0x8D
#define DPOff_EFLL2_En                       0x8E
#define DPOff_EFLL2_TccUD                    0x8F
#define DPOff_EFLL3_En                       0x90
#define DPOff_SEFLL_Ip                       0x91
#define DPOff_SEFLL_TDtMin                   0x92
#define DPOff_SEFLL_TDtRes                   0x93
#define DPOff_SEFLL_En                       0x94
#define DPOff_AutoOpenPowerFlowReduction     0x95
#define DPOff_AutoOpenPowerFlowTime          0x96
#define DPOff_LSRM_Timer                     0x97
#define DPOff_LSRM_En                        0x98
#define DPOff_Uv4_TDtMin                     0x99
#define DPOff_Uv4_TDtRes                     0x9A
#define DPOff_Uv4_Trm                        0x9B
#define DPOff_Uv4_Um_min                     0x9C
#define DPOff_Uv4_Um_max                     0x9D
#define DPOff_Uv4_Um_mid                     0x9E
#define DPOff_Uv4_Tlock                      0x9F
#define DPOff_Uv4_Utype                      0xA0
#define DPOff_Uv4_Voltages                   0xA1
#define DPOff_SingleTripleModeF              0xA2
#define DPOff_SingleTripleModeR              0xA3
#define DPOff_SinglePhaseVoltageDetect       0xA4
#define DPOff_Uv1_SingleTripleVoltageType    0xA5
#define DPOff_Ov1_SingleTripleVoltageType    0xA6
#define DPOff_LlbEnable                      0xA7
#define DPOff_LlbUM                          0xA8
#define DPOff_SectionaliserMode              0xA9
#define DPOff_OcDcr                          0xAA
#define DPOff_NpsDcr                         0xAB
#define DPOff_EfDcr                          0xAC
#define DPOff_SefDcr                         0xAD
#define DPOff_Ov3_Um                         0xAE
#define DPOff_Ov3_TDtMin                     0xAF
#define DPOff_Ov3_TDtRes                     0xB0
#define DPOff_Ov3_Trm                        0xB1
#define DPOff_Ov4_Um                         0xB2
#define DPOff_Ov4_TDtMin                     0xB3
#define DPOff_Ov4_TDtRes                     0xB4
#define DPOff_Ov4_Trm                        0xB5
#define DPOff_SequenceAdvanceStep            0xB6
#define DPOff_UV3_SSTOnly                    0xB7
#define DPOff_OV3MovingAverageMode           0xB8
#define DPOff_OV3MovingAverageWindow         0xB9
#define DPOff_ArveTripsToLockout             0xBA
#define DPOff_I2I1_Trm                       0xBB
#define DPOff_I2I1_Pickup                    0xBC
#define DPOff_I2I1_MinI2                     0xBD
#define DPOff_I2I1_TDtMin                    0xBE
#define DPOff_I2I1_TDtRes                    0xBF
#define DPOff_SEFF_Ip_HighPrec               0xC0
#define DPOff_SEFR_Ip_HighPrec               0xC1
#define DPOff_SEFLL_Ip_HighPrec              0xC2
#define DPOff_SSTControl_En                  0xC3
#define DPOff_SSTControl_Tst                 0xC4

/*   Ext3ProtectionStruct: Datapoint ID Offset from Base ID   */
#define DPOff_Yn_TDtMin                      0x0
#define DPOff_Yn_OperationalMode             0x1
#define DPOff_Yn_DirectionalMode             0x2
#define DPOff_Yn_Um                          0x3
#define DPOff_Yn_Ioper                       0x4
#define DPOff_Yn_TDtRes                      0x5
#define DPOff_Yn_FwdSusceptance              0x6
#define DPOff_Yn_RevSusceptance              0x7
#define DPOff_Yn_FwdConductance              0x8
#define DPOff_Yn_RevConductance              0x9
#define DPOff_Yn_Tr1                         0xA
#define DPOff_Yn_Tr2                         0xB
#define DPOff_Yn_Tr3                         0xC
#define DPOff_Yn_Tr4                         0xD
#define DPOff_OC1F_TccName                   0xE
#define DPOff_OC2F_TccName                   0xF
#define DPOff_OC1R_TccName                   0x10
#define DPOff_OC2R_TccName                   0x11
#define DPOff_NPS1F_TccName                  0x12
#define DPOff_NPS2F_TccName                  0x13
#define DPOff_NPS1R_TccName                  0x14
#define DPOff_NPS2R_TccName                  0x15
#define DPOff_EF1F_TccName                   0x16
#define DPOff_EF2F_TccName                   0x17
#define DPOff_EF1R_TccName                   0x18
#define DPOff_EF2R_TccName                   0x19
#define DPOff_OCLL1_TccName                  0x1A
#define DPOff_OCLL2_TccName                  0x1B
#define DPOff_NPSLL1_TccName                 0x1C
#define DPOff_NPSLL2_TccName                 0x1D
#define DPOff_EFLL1_TccName                  0x1E
#define DPOff_EFLL2_TccName                  0x1F
#define DPOff_DE_EF_AdvPolarDet              0x20
#define DPOff_DE_EF_MinNVD                   0x21
#define DPOff_DE_EF_MaxFwdAngle              0x22
#define DPOff_DE_EF_MinFwdAngle              0x23
#define DPOff_DE_EF_MaxRevAngle              0x24
#define DPOff_DE_EF_MinRevAngle              0x25
#define DPOff_DE_SEF_AdvPolarDet             0x26
#define DPOff_DE_SEF_MinNVD                  0x27
#define DPOff_DE_SEF_MaxFwdAngle             0x28
#define DPOff_DE_SEF_MinFwdAngle             0x29
#define DPOff_DE_SEF_MaxRevAngle             0x2A
#define DPOff_DE_SEF_MinRevAngle             0x2B
#define DPOff_DE_SEF_Polarisation            0x2C
#define DPOff_Hrm_IndA_NameExt               0x2D
#define DPOff_Hrm_IndB_NameExt               0x2E
#define DPOff_Hrm_IndC_NameExt               0x2F
#define DPOff_Hrm_IndD_NameExt               0x30
#define DPOff_Hrm_IndE_NameExt               0x31
#define DPOff_ROCOF_Trm                      0x32
#define DPOff_ROCOF_Pickup                   0x33
#define DPOff_ROCOF_TDtMin                   0x34
#define DPOff_ROCOF_TDtRes                   0x35
#define DPOff_VVS_Trm                        0x36
#define DPOff_VVS_Pickup                     0x37
#define DPOff_VVS_TDtMin                     0x38
#define DPOff_VVS_TDtRes                     0x39
#define DPOff_PDOP_Trm                       0x3A
#define DPOff_PDOP_Pickup                    0x3B
#define DPOff_PDOP_Angle                     0x3C
#define DPOff_PDOP_TDtMin                    0x3D
#define DPOff_PDOP_TDtRes                    0x3E
#define DPOff_PDUP_Trm                       0x3F
#define DPOff_PDUP_Pickup                    0x40
#define DPOff_PDUP_Angle                     0x41
#define DPOff_PDUP_TDtMin                    0x42
#define DPOff_PDUP_TDtRes                    0x43
#define DPOff_PDUP_TDtDis                    0x44

/*   MultiMaster60870Struct: Datapoint ID Offset from Base ID   */
#define DPOff_ScadaT10BRGConnectionEnable    0x0
#define DPOff_ScadaT10BRGAllowControls       0x1
#define DPOff_ScadaT10BRGConnectionName      0x2
#define DPOff_ScadaT10BRGChannelPort         0x3
#define DPOff_ScadaT10BRGIpVersion           0x4
#define DPOff_ScadaT10BRGSlaveTCPPort        0x5
#define DPOff_ScadaT10BRGConstraints         0x6
#define DPOff_ScadaT10BRGOriginatorAddress   0x7
#define DPOff_ScadaT10BRGMasterTCPPort       0x8
#define DPOff_ScadaT10BRGMasterIPv4Addr      0x9
#define DPOff_ScadaT10BRGMasterIPv6Addr      0xA
#define DPOff_ScadaT10BRGStatusConnectionState 0xB
#define DPOff_ScadaT10BRGStatusOriginatorAddress 0xC
#define DPOff_ScadaT10BRGStatusMasterTCPPort 0xD
#define DPOff_ScadaT10BRGStatusMasterIPv4Addr 0xE
#define DPOff_ScadaT10BRGStatusMasterIPv6Addr 0xF


/** @endcond DO_NOT_DOCUMENT   Doxygen documentation is not required. */
#endif // #ifndef _DBSCHEMA_INCLUDE/DBSCHEMA/DBGRPOFFSET_H_
