/**
 * @file include/dbschema/dbICDMapping.h
 * @brief This header defines the mapping of ICD data to datapoints.
 * 
 * This file is automatically generated and should not be edited manually.

 * Generated using the following input files:
 *   xslt/dbICDMapping_h.xsl : 1811 bytes, CRC32 = 2214189640 
 *   relay-datapoints-validated.xml : 18810769 bytes, CRC32 = 4257544476
 * 
 * Generated from the following database extract:
 *   Db Version : 28.0
 *   Db Tags    : NEW_ARCH,RC20-Security,RC20_USBOC,GooseSqNum,SdCard,VerizonAPN,Large_DbClientId,DB28_OSM_PART_CODES,DIR_POWER,MultiMaster60870,PIN_PUK,CBF_NOTICE,PMU_Retransmission,WEBSERVER
 *   Db Model   : RC20
 * 
 * @cond DO_NOT_DOCUMENT   Doxygen documentation is not required.
 */
#ifndef _DBSCHEMA_INCLUDE_DBSCHEMA_DBICDMAPPING_H_
#define _DBSCHEMA_INCLUDE_DBSCHEMA_DBICDMAPPING_H_

/**The datapoint to ICD data mapping definitions
 * Arguments: icdRef, dpName, type
 * icdRef      ICD data reference
 * dpName      Datapoint reference
 * type        Type of datapoint field mapped to the ICD data
 */
#define DATAREF_MAPPINGS \
\
DATAREF_MAPPING( GPNLD_PTOC1_Beh_Tr1, G1_OC1F_Tr1, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC1_Beh_Tr2, G1_OC1F_Tr2, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC1_Beh_Tr3, G1_OC1F_Tr3, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC1_Beh_Tr4, G1_OC1F_Tr4, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC2_Beh_Tr1, G1_OC2F_Tr1, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC2_Beh_Tr2, G1_OC2F_Tr2, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC2_Beh_Tr3, G1_OC2F_Tr3, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC2_Beh_Tr4, G1_OC2F_Tr4, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC3_Beh_Tr1, G1_OC3F_Tr1, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC3_Beh_Tr2, G1_OC3F_Tr2, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC3_Beh_Tr3, G1_OC3F_Tr3, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC3_Beh_Tr4, G1_OC3F_Tr4, DbValue ) \
DATAREF_MAPPING( EFLD_LLN0_Mod_stVal, SigCtrlEFOn, DbValue ) \
DATAREF_MAPPING( SEFLD_LLN0_Mod_stVal, SigCtrlSEFOn, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC4_Beh_SectionaliseG1, G1_SectionaliserMode, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC4_Beh_SectionaliseG2, G2_SectionaliserMode, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC4_Beh_SectionaliseG3, G3_SectionaliserMode, DbValue ) \
DATAREF_MAPPING( GPNLD_PTOC4_Beh_SectionaliseG4, G4_SectionaliserMode, DbValue ) \

/** @endcond DO_NOT_DOCUMENT   Doxygen documentation is not required. */
#endif // #ifndef _DBSCHEMA_INCLUDE/DBSCHEMA/DBICDMAPPING_H_
