/**
 * @file include/dbschema/dbSchemaUnits.h
 * @brief This generated file contains the macro definition providing details of
 *        every unit used by datapoints.
 * 
 * This file is automatically generated and should not be edited manually.

 * Generated using the following input files:
 *   xslt/dbSchemaUnits_h.xsl : 4468 bytes, CRC32 = 359177753 
 *   relay-datapoints-validated.xml : 18810769 bytes, CRC32 = 4257544476
 * 
 * Generated from the following database extract:
 *   Db Version : 28.0
 *   Db Tags    : NEW_ARCH,RC20-Security,RC20_USBOC,GooseSqNum,SdCard,VerizonAPN,Large_DbClientId,DB28_OSM_PART_CODES,DIR_POWER,MultiMaster60870,PIN_PUK,CBF_NOTICE,PMU_Retransmission,WEBSERVER
 *   Db Model   : RC20
 * 
 * @cond DO_NOT_DOCUMENT   Doxygen documentation is not required.
 */
#ifndef _DBSCHEMA_INCLUDE_DBSCHEMA_DBSCHEMAUNITS_H_
#define _DBSCHEMA_INCLUDE_DBSCHEMA_DBSCHEMAUNITS_H_

/** Count of unique units in the database */
#define DB_NUM_UNITS                     80

/** Length of all the unit strings including terminating NULL */
#define DB_LEN_UNITNAMES                 495

/** Count of datapoints with units in the database */
#define DB_DATAPOINT_UNITS               2344

/**The datapoint unit definitions
 * Arguments: name, type, desc, text
 * name        Unit name
 * unit        Unit text or symbol
 * len         Character length of text or symbol
 */
#define DBUNIT_DEFNS \
\
DBUNIT_DEFN( A, "A", 1 ) \
DBUNIT_DEFN( AH, "AH", 2 ) \
DBUNIT_DEFN( APerKA, "A/KA", 4 ) \
DBUNIT_DEFN( APerMV, "A/MV", 4 ) \
DBUNIT_DEFN( Addr, "Addr", 4 ) \
DBUNIT_DEFN( Addr_of_step, "Addr of step", 12 ) \
DBUNIT_DEFN( Ahrs, "Ahrs", 4 ) \
DBUNIT_DEFN( Amps, "Amps", 4 ) \
DBUNIT_DEFN( AuxConfig, "AuxConfig", 9 ) \
DBUNIT_DEFN( AvgPeriod, "AvgPeriod", 9 ) \
DBUNIT_DEFN( BattTestState, "BattTestState", 13 ) \
DBUNIT_DEFN( BlockPerTrip, "Block/Trip", 10 ) \
DBUNIT_DEFN( C, "C", 1 ) \
DBUNIT_DEFN( ChEvent, "ChEvent", 7 ) \
DBUNIT_DEFN( DateFormat, "DateFormat", 10 ) \
DBUNIT_DEFN( Dbug_str, "Dbug str", 8 ) \
DBUNIT_DEFN( Degree, "Degree", 6 ) \
DBUNIT_DEFN( EnDis, "EnDis", 5 ) \
DBUNIT_DEFN( EnPerDisable, "En/Disable", 10 ) \
DBUNIT_DEFN( Hrs, "Hrs", 3 ) \
DBUNIT_DEFN( Hz, "Hz", 2 ) \
DBUNIT_DEFN( HzPers, "Hz/s", 4 ) \
DBUNIT_DEFN( HzPersec, "Hz/sec", 6 ) \
DBUNIT_DEFN( KV, "KV", 2 ) \
DBUNIT_DEFN( Mins, "Mins", 4 ) \
DBUNIT_DEFN( OkFail, "OkFail", 6 ) \
DBUNIT_DEFN( OkSCct, "OkSCct", 6 ) \
DBUNIT_DEFN( OnOff, "OnOff", 5 ) \
DBUNIT_DEFN( Ops, "Ops", 3 ) \
DBUNIT_DEFN( PCT, "%", 1 ) \
DBUNIT_DEFN( Per_sec, "/ sec", 5 ) \
DBUNIT_DEFN( Percent, "Percent", 7 ) \
DBUNIT_DEFN( RdyNr, "RdyNr", 5 ) \
DBUNIT_DEFN( RelayState, "RelayState", 10 ) \
DBUNIT_DEFN( TransPerCont, "Trans/Cont", 10 ) \
DBUNIT_DEFN( TripMode, "TripMode", 8 ) \
DBUNIT_DEFN( Trip_Num, "Trip #", 6 ) \
DBUNIT_DEFN( USense, "USense", 6 ) \
DBUNIT_DEFN( Un, "Un", 2 ) \
DBUNIT_DEFN( V, "V", 1 ) \
DBUNIT_DEFN( VPerA, "V/A", 3 ) \
DBUNIT_DEFN( V_x0_001x, "V(x0.001)", 9 ) \
DBUNIT_DEFN( V_x0_01x, "V(x0.01)", 8 ) \
DBUNIT_DEFN( W, "W", 1 ) \
DBUNIT_DEFN( dPId, "dPId", 4 ) \
DBUNIT_DEFN( dUnits, "dUnits", 6 ) \
DBUNIT_DEFN( days, "days", 4 ) \
DBUNIT_DEFN( deg, "deg", 3 ) \
DBUNIT_DEFN( degree, "degree", 6 ) \
DBUNIT_DEFN( degrees, "degrees", 7 ) \
DBUNIT_DEFN( kA, "kA", 2 ) \
DBUNIT_DEFN( kV, "kV", 2 ) \
DBUNIT_DEFN( kVA, "kVA", 3 ) \
DBUNIT_DEFN( kVAh, "kVAh", 4 ) \
DBUNIT_DEFN( kVAr, "kVAr", 4 ) \
DBUNIT_DEFN( kVArh, "kVArh", 5 ) \
DBUNIT_DEFN( kW, "kW", 2 ) \
DBUNIT_DEFN( kWh, "kWh", 3 ) \
DBUNIT_DEFN( km, "km", 2 ) \
DBUNIT_DEFN( m, "m", 1 ) \
DBUNIT_DEFN( mA, "mA", 2 ) \
DBUNIT_DEFN( mHz, "mHz", 3 ) \
DBUNIT_DEFN( mSi, "mSi", 3 ) \
DBUNIT_DEFN( mV, "mV", 2 ) \
DBUNIT_DEFN( m_s, "m:s", 3 ) \
DBUNIT_DEFN( microdegree, "microdegree", 11 ) \
DBUNIT_DEFN( mill, "mill", 4 ) \
DBUNIT_DEFN( millidegree, "millidegree", 11 ) \
DBUNIT_DEFN( mills, "mills", 5 ) \
DBUNIT_DEFN( min, "min", 3 ) \
DBUNIT_DEFN( minutes, "minutes", 7 ) \
DBUNIT_DEFN( ms, "ms", 2 ) \
DBUNIT_DEFN( ohms, "ohms", 4 ) \
DBUNIT_DEFN( ohmsPerkm, "ohms/km", 7 ) \
DBUNIT_DEFN( operations, "operations", 10 ) \
DBUNIT_DEFN( ppm__part_per_millionx, "ppm (part per million)", 22 ) \
DBUNIT_DEFN( pu, "pu", 2 ) \
DBUNIT_DEFN( s, "s", 1 ) \
DBUNIT_DEFN( seconds, "seconds", 7 ) \
DBUNIT_DEFN( us, "us", 2 ) \

/** @endcond DO_NOT_DOCUMENT   Doxygen documentation is not required. */
#endif // #ifndef _DBSCHEMA_INCLUDE/DBSCHEMA/DBSCHEMAUNITS_H_
