/**
 * @file include/dbschema/dbSigData.h
 * @brief This generated file contains the macro definition providing details of
 *        the signal pairing relationships.
 * 
 * This file is automatically generated and should not be edited manually.

 * Generated using the following input files:
 *   xslt/dbSigData_h.xsl : 5454 bytes, CRC32 = 3145124183 
 *   relay-datapoints-validated.xml : 18810769 bytes, CRC32 = 4257544476
 * 
 * Generated from the following database extract:
 *   Db Version : 28.0
 *   Db Tags    : NEW_ARCH,RC20-Security,RC20_USBOC,GooseSqNum,SdCard,VerizonAPN,Large_DbClientId,DB28_OSM_PART_CODES,DIR_POWER,MultiMaster60870,PIN_PUK,CBF_NOTICE,PMU_Retransmission,WEBSERVER
 *   Db Model   : RC20
 * 
 * @cond DO_NOT_DOCUMENT   Doxygen documentation is not required.
 */
#ifndef _DBSCHEMA_INCLUDE_DBSCHEMA_DBSIGDATA_H_
#define _DBSCHEMA_INCLUDE_DBSCHEMA_DBSIGDATA_H_

/**The Signal Parent - List pairing definitions
 * Arguments: signal, list
 * signal      Name of the signal
 * list        Name of the paired SignalList
 */
#define SIGNAL_LIST_DATA \
\
SIGNAL_LIST( SigWarning, SigListWarning ), \
SIGNAL_LIST( SigMalfunction, SigListMalfunction ), \

/**The Signal Parent - Child pairing definitions
 * Arguments (SIGNAL_DATA): signal, text
 * Arguments (SIGNAL_DATA_CHILD): parent, signal, text
 * parent      Name of the parent signal (only for child signals)
 * signal      Name of the signal
 * text        English description of the Signal
 */
#define SIGNAL_PAIR_DATA \
\
SIGNAL_DATA( SigOpen, "Open(Any)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenLogic, "Open(Logic)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenRemote, "Open(Remote)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenSCADA, "Open(SCADA)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenIO, "Open(IO)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenLocal, "Open(Local)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenMMI, "Open(HMI)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenPC, "Open(PC)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigSwitchManualTrip, "Open(Manual)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenUndef, "Open(Undefined)" ), \
SIGNAL_DATA_CHILD( SigOpen, SigOpenSim, "Open(Sim)" ), \
\
SIGNAL_DATA( SigAlarm, "Alarm(Any)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOf, "A(OF)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmUf, "A(UF)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPhA, "A(PhA)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPhB, "A(PhB)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPhC, "A(PhC)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPhN, "A(PhN)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmHrm, "A(Any HRM)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOc, "A(OC)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmEf, "A(EF)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmSef, "A(SEF)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmUv, "A(UV)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOv, "A(OV)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmNps, "A(NPS)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOcll1, "A(OCLL1)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOcll2, "A(OCLL2)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmOcll3, "A(OCLL3)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmNpsll1, "A(NPSLL1)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmNpsll2, "A(NPSLL2)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmNpsll3, "A(NPSLL3)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmEfll1, "A(EFLL1)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmEfll2, "A(EFLL2)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmEfll3, "A(EFLL3)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmSefll, "A(SEFLL)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmYn, "A(Yn)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmI2I1, "A(I2/I1)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmROCOF, "A(ROCOF)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmVVS, "A(VVS)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPDOP, "A(PDOP)" ), \
SIGNAL_DATA_CHILD( SigAlarm, SigAlarmPDUP, "A(PDUP)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc1F, "A(OC1+)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc2F, "A(OC2+)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc3F, "A(OC3+)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc1R, "A(OC1-)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc2R, "A(OC2-)" ), \
SIGNAL_DATA_CHILD( SigAlarmOc, SigAlarmOc3R, "A(OC3-)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf1F, "A(EF1+)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf2F, "A(EF2+)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf3F, "A(EF3+)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf1R, "A(EF1-)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf2R, "A(EF2-)" ), \
SIGNAL_DATA_CHILD( SigAlarmEf, SigAlarmEf3R, "A(EF3-)" ), \
SIGNAL_DATA_CHILD( SigAlarmSef, SigAlarmSefF, "A(SEF+)" ), \
SIGNAL_DATA_CHILD( SigAlarmSef, SigAlarmSefR, "A(SEF-)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv, SigAlarmUv1, "A(UV1)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv, SigAlarmUv2, "A(UV2)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv, SigAlarmUv3, "A(UV3)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv, SigAlarmUv4, "A(UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv4, SigAlarmUabcUv4, "A(Uabc UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv4, SigAlarmUrstUv4, "A(Urst UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv4, SigAlarmUv4Midpoint, "A(UV4 Sag Midpoint)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv4Midpoint, SigAlarmUabcUv4Midpoint, "A(Uabc UV4 Sag Midpoint)" ), \
SIGNAL_DATA_CHILD( SigAlarmUv4Midpoint, SigAlarmUrstUv4Midpoint, "A(Urst UV4 Sag Midpoint)" ), \
SIGNAL_DATA_CHILD( SigAlarmOv, SigAlarmOv1, "A(OV1)" ), \
SIGNAL_DATA_CHILD( SigAlarmOv, SigAlarmOv2, "A(OV2)" ), \
SIGNAL_DATA_CHILD( SigAlarmOv, SigAlarmOv3, "A(OV3)" ), \
SIGNAL_DATA_CHILD( SigAlarmOv, SigAlarmOv4, "A(OV4)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps1F, "A(NPS1+)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps2F, "A(NPS2+)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps3F, "A(NPS3+)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps1R, "A(NPS1-)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps2R, "A(NPS2-)" ), \
SIGNAL_DATA_CHILD( SigAlarmNps, SigAlarmNps3R, "A(NPS3-)" ), \
\
SIGNAL_DATA( SigClosed, "Closed(Any)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedLogic, "Closed(Logic)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedAR, "Closed(AR)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedRemote, "Closed(Remote)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedSCADA, "Closed(SCADA)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedIO, "Closed(IO)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedLocal, "Closed(Local)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedMMI, "Closed(HMI)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedPC, "Closed(PC)" ), \
SIGNAL_DATA_CHILD( SigClosed, SigClosedUndef, "Closed(Undefined)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedACO, "Closed(ACO)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedAR_OcEf, "Closed(AR OC/NPS/EF/SEF)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedAR_Sef, "Closed(AR OC/NPS/EF/SEF)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedABR, "Closed(ABR)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedAR_VE, "Closed(AR VE)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedABRAutoOpen, "Closed(ABR AutoOpen)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedUV3AutoClose, "Closed(UV3 AutoClose)" ), \
SIGNAL_DATA_CHILD( SigClosedAR, SigClosedAutoSync, "Closed(Auto-Sync)" ), \
SIGNAL_DATA_CHILD( SigClosedAR_VE, SigClosedAR_Uv, "Closed(AR UV)" ), \
SIGNAL_DATA_CHILD( SigClosedAR_VE, SigClosedAR_Ov, "Closed(AR OV)" ), \
\
SIGNAL_DATA( SigMalfunction, "Malfunction" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigRTCHwFault, "RTC Hardware Fault" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfRc10, "Controller Fault" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfOsm, "OSM Fault" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfLoadSavedDb, "Incorrect DB Values Loaded" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfOsmA, "Fault Ph A" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfOsmB, "Fault Ph B" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigMalfOsmC, "Fault Ph C" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigBatteryTestFaulty, "Battery Test Circuit Fault" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigGPSMalfunction, "GPS Malfunction" ), \
SIGNAL_DATA_CHILD( SigMalfunction, sigFirmwareHardwareMismatch, "Firmware/Hardware Mismatch" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigUSBOCMalfunction, "USB Overcurrent" ), \
SIGNAL_DATA_CHILD( SigMalfunction, SigCBFMalf, "CBF Malfunctions" ), \
SIGNAL_DATA_CHILD( SigMalfRc10, SigExtSupplyStatusOverLoad, "External Load Overload" ), \
SIGNAL_DATA_CHILD( SigMalfRc10, SigMalfComms, "Module Comms Error" ), \
SIGNAL_DATA_CHILD( SigMalfRc10, SigMalfModule, "Controller Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRc10, SigMalfCanBus, "CAN Bus Malfunction" ), \
SIGNAL_DATA_CHILD( SigMalfComms, SigMalfSimComms, "SIM Comms Error" ), \
SIGNAL_DATA_CHILD( SigMalfComms, SigMalfIo1Comms, "I/O1 Comms Error" ), \
SIGNAL_DATA_CHILD( SigMalfComms, SigMalfIo2Comms, "I/O2 Comms Error" ), \
SIGNAL_DATA_CHILD( SigMalfComms, SigMalfPanelComms, "Panel Comms Error" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfRelay, "Relay Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfIo1Fault, "I/O1 Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfIo2Fault, "I/O2 Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigBatteryChargerStatusFails, "Battery Charger Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigModuleSimHealthFault, "SIM Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigModuleTypeSimDisconnected, "SIM Disconnected" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfPanelModule, "Panel Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigOperationFaultCap, "Capacitor Voltage Abnormal" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfSimRunningMiniBootloader, "SIM in Mini Bootloader Mode" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfSectionaliserMismatch, "Sectionaliser configuration mismatch" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigModuleTypePscDisconnected, "PSC Disconnected" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfPscRunningMiniBootloader, "PSC in Mini Bootloader Mode" ), \
SIGNAL_DATA_CHILD( SigMalfModule, SigMalfPscFault, "PSC Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfRelayLog, "Log process fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfRel03, "REL-03 Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfRel15, "REL-15 Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfRel15_4G, "REL-15-4G Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfWLAN, "WLAN Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfRel20, "REL-20 Module Fault" ), \
SIGNAL_DATA_CHILD( SigMalfRelay, SigMalfAnalogBoard, "Analog Board Error" ), \
SIGNAL_DATA_CHILD( SigModuleSimHealthFault, SigOSMActuatorFaultStatusQ503Failed, "OSM Actuator FaultStatus Q503Failed" ), \
SIGNAL_DATA_CHILD( SigModuleSimHealthFault, SigOSMActuatorFaultStatusQ503FailedA, "" ), \
SIGNAL_DATA_CHILD( SigModuleSimHealthFault, SigOSMActuatorFaultStatusQ503FailedB, "" ), \
SIGNAL_DATA_CHILD( SigModuleSimHealthFault, SigOSMActuatorFaultStatusQ503FailedC, "" ), \
SIGNAL_DATA_CHILD( SigModuleSimHealthFault, SigModuleSimUnhealthy, "SIM Module Health Fault" ), \
SIGNAL_DATA_CHILD( SigMalfCanBus, SigCANControllerOverrun, "CANControllerOverrun" ), \
SIGNAL_DATA_CHILD( SigMalfCanBus, SigCANControllerError, "CANControllerError" ), \
SIGNAL_DATA_CHILD( SigMalfCanBus, SigCANMessagebufferoverflow, "CANMessagebufferoverflow" ), \
SIGNAL_DATA_CHILD( SigMalfCanBus, SigRelayCANMessagebufferoverflow, "CANMessagebufferoverflow" ), \
SIGNAL_DATA_CHILD( SigMalfCanBus, SigRelayCANControllerError, "CANControllerError" ), \
SIGNAL_DATA_CHILD( SigMalfOsm, SigTripCloseRequestStatusTripFail, "Excessive To" ), \
SIGNAL_DATA_CHILD( SigMalfOsm, SigTripCloseRequestStatusCloseFail, "Excessive Tc" ), \
SIGNAL_DATA_CHILD( SigMalfOsm, SigOSMActuatorFaultStatusCoilOc, "OSM Coil OC" ), \
SIGNAL_DATA_CHILD( SigMalfOsm, SigOsmActuatorFaultStatusCoilSc, "OSM Coil SC" ), \
SIGNAL_DATA_CHILD( SigMalfOsm, SigOsmLimitFaultStatusFault, "OSM Limit Switch Fault" ), \
SIGNAL_DATA_CHILD( SigMalfOsmA, SigOSMActuatorFaultStatusCoilOcA, "Coil Ph A OC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmA, SigOsmActuatorFaultStatusCoilScA, "Coil Ph A SC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmA, SigOsmLimitFaultStatusFaultA, "Limit Switch Fault Ph A" ), \
SIGNAL_DATA_CHILD( SigMalfOsmA, SigTripCloseRequestStatusTripFailA, "Excessive To Ph A" ), \
SIGNAL_DATA_CHILD( SigMalfOsmA, SigTripCloseRequestStatusCloseFailA, "Excessive Tc Ph A" ), \
SIGNAL_DATA_CHILD( SigMalfOsmB, SigOSMActuatorFaultStatusCoilOcB, "Coil Ph B OC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmB, SigOsmActuatorFaultStatusCoilScB, "Coil Ph B SC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmB, SigOsmLimitFaultStatusFaultB, "Limit Switch Fault Ph B" ), \
SIGNAL_DATA_CHILD( SigMalfOsmB, SigTripCloseRequestStatusTripFailB, "Excessive To Ph B" ), \
SIGNAL_DATA_CHILD( SigMalfOsmB, SigTripCloseRequestStatusCloseFailB, "Excessive Tc Ph B" ), \
SIGNAL_DATA_CHILD( SigMalfOsmC, SigOSMActuatorFaultStatusCoilOcC, "Coil Ph C OC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmC, SigOsmActuatorFaultStatusCoilScC, "Coil Ph C SC" ), \
SIGNAL_DATA_CHILD( SigMalfOsmC, SigOsmLimitFaultStatusFaultC, "Limit Switch Fault Ph C" ), \
SIGNAL_DATA_CHILD( SigMalfOsmC, SigTripCloseRequestStatusTripFailC, "Excessive To Ph C" ), \
SIGNAL_DATA_CHILD( SigMalfOsmC, SigTripCloseRequestStatusCloseFailC, "Excessive Tc Ph C" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCOnboard, "USB Overcurrent Onboard" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCExternal, "USB Overcurrent External" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCModem, "USB Overcurrent Modem" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCWifi, "USB Overcurrent wifi" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCGPS, "USB Overcurrent GPS" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCOnboardA, "USB Overcurrent USB A" ), \
SIGNAL_DATA_CHILD( SigUSBOCMalfunction, SigUSBOCOnboardB, "USB Overcurrent USB B" ), \
SIGNAL_DATA_CHILD( SigCBFMalf, SigCBFMalfunction, "CBF Malfunction" ), \
SIGNAL_DATA_CHILD( SigCBFMalf, SigCBFBackupTrip, "CBF Backup Trip" ), \
\
SIGNAL_DATA( SigWarning, "Warning" ), \
SIGNAL_DATA_CHILD( SigWarning, SigCtrlHltOn, "Hot Line Tag On" ), \
SIGNAL_DATA_CHILD( SigWarning, SigStatusCloseBlocking, "Logical Block Close" ), \
SIGNAL_DATA_CHILD( SigWarning, UpdateFailed, "Update Failed" ), \
SIGNAL_DATA_CHILD( SigWarning, UpdateReverted, "Update Reverted" ), \
SIGNAL_DATA_CHILD( SigWarning, UpdateSettingsLogFailed, "Update Settings or Logs Failed" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUSBUnsupported, "USB Unsupported" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUSBMismatched, "USB Mismatched" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSimNotCalibrated, "SIM Not Calibrated" ), \
SIGNAL_DATA_CHILD( SigWarning, SigLineSupplyStatusAbnormal, "Line Supply Status Abnormal" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUSBHostOff, "USB Host Off" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSupplyUnhealthy, "Source Not Healthy" ), \
SIGNAL_DATA_CHILD( SigWarning, ACOUnhealthy, "ACO Unhealthy" ), \
SIGNAL_DATA_CHILD( SigWarning, SigP2PCommFail, "Peer Comms Failed" ), \
SIGNAL_DATA_CHILD( SigWarning, SigOperWarning, "Operational Warning" ), \
SIGNAL_DATA_CHILD( SigWarning, SigStatusDialupFailed, "Dial-up Failed" ), \
SIGNAL_DATA_CHILD( SigWarning, SigBatteryStatusAbnormal, "Battery Status Abnormal" ), \
SIGNAL_DATA_CHILD( SigWarning, SigBatteryChargerStatusLowPower, "Battery Charger State: Low Power" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUPSStatusAcOff, "AC Off (On Battery Supply)" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUPSStatusBatteryOff, "Battery Off (On AC Supply)" ), \
SIGNAL_DATA_CHILD( SigWarning, SigUPSPowerDown, "Critical Battery Level" ), \
SIGNAL_DATA_CHILD( SigWarning, SigLineSupplyStatusOff, "Line Supply Status Off" ), \
SIGNAL_DATA_CHILD( SigWarning, SigBatteryTestCheckBattery, "Check Battery" ), \
SIGNAL_DATA_CHILD( SigWarning, SigIncorrectPhaseSeq, "Incorrect Phase Sequence" ), \
SIGNAL_DATA_CHILD( SigWarning, SigLogicConfigIssue, "Logic Configuration Issue" ), \
SIGNAL_DATA_CHILD( SigWarning, SigStatusIEC61499FailedFBOOT, "SGA fboot Failed" ), \
SIGNAL_DATA_CHILD( SigWarning, SigGPSUnplugged, "GPS Unplugged" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSimAndOsmModelMismatch, "SIM and OSM Model Mismatch" ), \
SIGNAL_DATA_CHILD( SigWarning, LogicSGAStopped, "Logic/SGA Stopped" ), \
SIGNAL_DATA_CHILD( SigWarning, LogicSGAThrottling, "Logic/SGA Throttling" ), \
SIGNAL_DATA_CHILD( SigWarning, LoadedScadaRestartReqWarning, "SCADA Config requires RC restart" ), \
SIGNAL_DATA_CHILD( SigWarning, SNTPUnableToSync, "SNTP Unable to Sync" ), \
SIGNAL_DATA_CHILD( SigWarning, CanBusHighPower, "CAN Bus High Power" ), \
SIGNAL_DATA_CHILD( SigWarning, SigCorruptedPartition, "Corrupted Partition" ), \
SIGNAL_DATA_CHILD( SigWarning, SigRLM20UpgradeFailure, "RLM-20 Upgrade Failure" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardError, "SIM Card Error" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardPINReqd, "SIM Card PIN Required" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardPINError, "SIM Card PIN Error" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardBlockedByPIN, "SIM Card Blocked" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardPUKError, "SIM Card PUK Error" ), \
SIGNAL_DATA_CHILD( SigWarning, SigSIMCardBlockedPerm, "SIM Card Blocked Permanently" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchPositionStatusUnavailable, "OSM Position Status Unavailable" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchDisconnectionStatus, "OSM Disconnected" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLockoutStatusMechaniclocked, "Mechanically Locked" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigDriverStatusNotReady, "SIM Caps Not Charged" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchDisconnectionStatusA, "Disconnected Ph A" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchDisconnectionStatusB, "Disconnected Ph B" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchDisconnectionStatusC, "Disconnected Ph C" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLockoutStatusMechaniclockedA, "Mechanically Locked Ph A" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLockoutStatusMechaniclockedB, "Mechanically Locked Ph B" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLockoutStatusMechaniclockedC, "Mechanically Locked Ph C" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLogicallyLockedA, "SW Locked Ph A" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLogicallyLockedB, "SW Locked Ph B" ), \
SIGNAL_DATA_CHILD( SigOperWarning, SigSwitchLogicallyLockedC, "SW Locked Ph C" ), \
SIGNAL_DATA_CHILD( LogicSGAStopped, LogicSGAStoppedLogic, "Logic/SGA Stopped Logic" ), \
SIGNAL_DATA_CHILD( LogicSGAStopped, LogicSGAStoppedSGA, "Logic/SGA Stopped SGA" ), \
SIGNAL_DATA_CHILD( LogicSGAThrottling, LogicSGAThrottlingLogic, "Logic/SGA Throttling Logic" ), \
SIGNAL_DATA_CHILD( LogicSGAThrottling, LogicSGAThrottlingSGA, "Logic/SGA Throttling SGA" ), \
\
SIGNAL_DATA( SigGenProtInit, "Prot initiated" ), \
SIGNAL_DATA_CHILD( SigGenProtInit, SigPickup, "Pickup" ), \
SIGNAL_DATA_CHILD( SigGenProtInit, SigGenARInit, "AR initiated" ), \
SIGNAL_DATA_CHILD( SigGenProtInit, SigGenARInitA, "AR initiated SW Ph A" ), \
SIGNAL_DATA_CHILD( SigGenProtInit, SigGenARInitB, "AR initiated SW Ph B" ), \
SIGNAL_DATA_CHILD( SigGenProtInit, SigGenARInitC, "AR initiated SW Ph C" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOcll, "P(OCLL3)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupEfll, "P(EFLL3)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOf, "P(OF)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupUf, "P(UF)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPhA, "P(PhA)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPhB, "P(PhB)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPhC, "P(PhC)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPhN, "P(PhN)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupHrm, "P(Any HRM)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOcll1, "P(OCLL1)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOcll2, "P(OCLL2)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupNpsll1, "P(NPSLL1)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupNpsll2, "P(NPSLL2)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupNpsll3, "P(NPSLL3)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupEfll1, "P(EFLL1)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupEfll2, "P(EFLL2)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupSefll, "P(SEFLL)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOc, "P(OC)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupEf, "P(EF)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupSef, "P(SEF)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupUv, "P(UV)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupOv, "P(OV)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupABR, "P(ABR)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupNps, "P(NPS)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupYn, "P(Yn)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupI2I1, "P(I2/I1)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupROCOF, "P(ROCOF)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupVVS, "P(VVS)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPDOP, "P(PDOP)" ), \
SIGNAL_DATA_CHILD( SigPickup, SigPickupPDUP, "P(PDUP)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc1F, "P(OC1+)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc2F, "P(OC2+)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc3F, "P(OC3+)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc1R, "P(OC1-)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc2R, "P(OC2-)" ), \
SIGNAL_DATA_CHILD( SigPickupOc, SigPickupOc3R, "P(OC3-)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf1F, "P(EF1+)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf2F, "P(EF2+)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf3F, "P(EF3+)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf1R, "P(EF1-)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf2R, "P(EF2-)" ), \
SIGNAL_DATA_CHILD( SigPickupEf, SigPickupEf3R, "P(EF3-)" ), \
SIGNAL_DATA_CHILD( SigPickupSef, SigPickupSefF, "P(SEF+)" ), \
SIGNAL_DATA_CHILD( SigPickupSef, SigPickupSefR, "P(SEF-)" ), \
SIGNAL_DATA_CHILD( SigPickupUv, SigPickupUv1, "P(UV1)" ), \
SIGNAL_DATA_CHILD( SigPickupUv, SigPickupUv2, "P(UV2)" ), \
SIGNAL_DATA_CHILD( SigPickupUv, SigPickupUv3, "P(UV3)" ), \
SIGNAL_DATA_CHILD( SigPickupUv, SigPickupUv4, "P(UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigPickupUv4, SigPickupUabcUv4, "P(Uabc UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigPickupUv4, SigPickupUrstUv4, "P(Urst UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigPickupOv, SigPickupOv1, "P(OV1)" ), \
SIGNAL_DATA_CHILD( SigPickupOv, SigPickupOv2, "P(OV2)" ), \
SIGNAL_DATA_CHILD( SigPickupOv, SigPickupOv3, "P(OV3)" ), \
SIGNAL_DATA_CHILD( SigPickupOv, SigPickupOv4, "P(OV4)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps1F, "P(NPS1+)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps2F, "P(NPS2+)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps3F, "P(NPS3+)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps1R, "P(NPS1-)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps2R, "P(NPS2-)" ), \
SIGNAL_DATA_CHILD( SigPickupNps, SigPickupNps3R, "P(NPS3-)" ), \
\
SIGNAL_DATA( SigFaultTarget, "Fault Target Set" ), \
SIGNAL_DATA_CHILD( SigFaultTarget, SigFaultTargetOpen, "Open Fault Target Set" ), \
SIGNAL_DATA_CHILD( SigFaultTarget, SigFaultTargetNonOpen, "Fault Target Non-Open" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenGrp1, "Group 1 Trip" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenGrp2, "Group 2 Trip" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenGrp3, "Group 3 Trip" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenGrp4, "Group 4 Trip" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenACO, "Open(ACO)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenProt, "Open(Prot)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetOpen, SigOpenABRAutoOpen, "Open(ABR AutoOpen)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenOf, "Open(OF)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenUf, "Open(UF)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPhA, "Open(PhA)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPhB, "Open(PhB)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPhC, "Open(PhC)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPhN, "Open(PhN)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenHrm, "Open(Any HRM)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenNpsll1, "Open(NPSLL1)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenNpsll2, "Open(NPSLL2)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenNpsll3, "Open(NPSLL3)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenSefll, "Open(SEFLL)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenOc, "Open(OC)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenEf, "Open(EF)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenSef, "Open(SEF)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenUv, "Open(UV)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenOv, "Open(OV)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenLSRM, "Open(LSRM)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenSectionaliser, "Open(Sectionaliser)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenOcllTop, "Open(OCLL)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenEfllTop, "Open(EFLL)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenNps, "Open(NPS)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenYn, "Open(Yn)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenI2I1, "Open(I2/I1)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenROCOF, "Open(ROCOF)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenVVS, "Open(VVS)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPDOP, "Open(PDOP)" ), \
SIGNAL_DATA_CHILD( SigOpenProt, SigOpenPDUP, "Open(PDUP)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc1F, "Open(OC1+)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc2F, "Open(OC2+)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc3F, "Open(OC3+)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc1R, "Open(OC1-)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc2R, "Open(OC2-)" ), \
SIGNAL_DATA_CHILD( SigOpenOc, SigOpenOc3R, "Open(OC3-)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf1F, "Open(EF1+)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf2F, "Open(EF2+)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf3F, "Open(EF3+)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf1R, "Open(EF1-)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf2R, "Open(EF2-)" ), \
SIGNAL_DATA_CHILD( SigOpenEf, SigOpenEf3R, "Open(EF3-)" ), \
SIGNAL_DATA_CHILD( SigOpenSef, SigOpenSefF, "Open(SEF+)" ), \
SIGNAL_DATA_CHILD( SigOpenSef, SigOpenSefR, "Open(SEF-)" ), \
SIGNAL_DATA_CHILD( SigOpenUv, SigOpenUv1, "Open(UV1)" ), \
SIGNAL_DATA_CHILD( SigOpenUv, SigOpenUv2, "Open(UV2)" ), \
SIGNAL_DATA_CHILD( SigOpenUv, SigOpenUv3, "Open(UV3)" ), \
SIGNAL_DATA_CHILD( SigOpenUv, SigOpenUv4, "Open(UV4 Sag)" ), \
SIGNAL_DATA_CHILD( SigOpenOv, SigOpenOv1, "Open(OV1)" ), \
SIGNAL_DATA_CHILD( SigOpenOv, SigOpenOv2, "Open(OV2)" ), \
SIGNAL_DATA_CHILD( SigOpenOv, SigOpenOv3, "Open(OV3)" ), \
SIGNAL_DATA_CHILD( SigOpenOv, SigOpenOv4, "Open(OV4)" ), \
SIGNAL_DATA_CHILD( SigOpenOcllTop, SigOpenOcll, "Open(OCLL3)" ), \
SIGNAL_DATA_CHILD( SigOpenOcllTop, SigOpenOcll1, "Open(OCLL1)" ), \
SIGNAL_DATA_CHILD( SigOpenOcllTop, SigOpenOcll2, "Open(OCLL2)" ), \
SIGNAL_DATA_CHILD( SigOpenEfllTop, SigOpenEfll, "Open(EFLL3)" ), \
SIGNAL_DATA_CHILD( SigOpenEfllTop, SigOpenEfll1, "Open(EFLL1)" ), \
SIGNAL_DATA_CHILD( SigOpenEfllTop, SigOpenEfll2, "Open(EFLL2)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps1F, "Open(NPS1+)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps2F, "Open(NPS2+)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps3F, "Open(NPS3+)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps1R, "Open(NPS1-)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps2R, "Open(NPS2-)" ), \
SIGNAL_DATA_CHILD( SigOpenNps, SigOpenNps3R, "Open(NPS3-)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigMntActivated, "MNT Exceeded" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Midpoint, "Open(UV4 Sag Mid)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ua, "UV4 Sag(Ua)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ub, "UV4 Sag(Ub)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Uc, "UV4 Sag(Uc)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ur, "UV4 Sag(Ur)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Us, "UV4 Sag(Us)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ut, "UV4 Sag(Ut)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Uab, "UV4 Sag(Uab)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ubc, "UV4 Sag(Ubc)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Uca, "UV4 Sag(Uca)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Urs, "UV4 Sag(Urs)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Ust, "UV4 Sag(Ust)" ), \
SIGNAL_DATA_CHILD( SigFaultTargetNonOpen, SigOpenUv4Utr, "UV4 Sag(Utr)" ), \
SIGNAL_DATA_CHILD( SigOpenUv4Midpoint, SigOpenUabcUv4Midpoint, "Open(Uabc UV4 Sag Midpoint)" ), \
SIGNAL_DATA_CHILD( SigOpenUv4Midpoint, SigOpenUrstUv4Midpoint, "Open(Urst UV4 Sag Midpoint)" ), \

/** @endcond DO_NOT_DOCUMENT   Doxygen documentation is not required. */
#endif // #ifndef _DBSCHEMA_INCLUDE/DBSCHEMA/DBSIGDATA_H_
