INCLUDE(CMakeForceCompiler)
SET(CMAKE_C_STANDARD 99)
SET(CMAKE_SYSTEM_NAME Windows)
SET(LWS_WITHOUT_TESTAPPS ON)
SET(LWS_WITHOUT_TEST_SERVER ON)
SET(LWS_WITHOUT_TEST_SERVER_EXTPOLL ON)
SET(LWS_WITHOUT_TEST_PING ON)
SET(LWS_WITHOUT_TEST_CLIENT ON)
# search for programs in the build host directories
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(BUILD_STATIC_TARGET true)
